/*
 * SCCPConstants.h
 *
 *  Created on: 17-Jul-2016
 *      Author: Deb
 */

#ifndef PLUGINS_SCCP_INC_SCCPCONSTANTS_H_
#define PLUGINS_SCCP_INC_SCCPCONSTANTS_H_

#define SCCP_CR 1
#define SCCP_CC 2
#define SCCP_CREF 3
#define SCCP_RLSD 4
#define SCCP_RLC 5
#define SCCP_DT1 6
#define SCCP_DT2 7
#define SCCP_AK 8
#define SCCP_UDT 9
#define SCCP_UDTS 10
#define SCCP_ED 11
#define SCCP_EA 12
#define SCCP_RSR 13
#define SCCP_RSC 14
#define SCCP_RSC 14
#define SCCP_ERR 15
#define SCCP_IT 16
#define SCCP_XUDT 17
#define SCCP_XUDTS 18
#define SCCP_LUDT 19
#define SCCP_LUDTS 20

#define SCCP_PROTOCOL_CLASS_0 0x00
#define SCCP_PROTOCOL_CLASS_1 0x01
#define SCCP_PROTOCOL_CLASS_2 0x02
#define SCCP_PROTOCOL_CLASS_3 0x03

#define SCCP_END_OF_OPTIONAL_PARAMETERS 0x00
#define SCCP_DESTINATION_LOCAL_REFERENCE 0x01
#define SCCP_SOURCE_LOCAL_REFERENCE 0x02
#define SCCP_CALLED_PARTY_ADDRESS 0x03
#define SCCP_CALLING_PARTY_ADDRESS 0x04
#define SCCP_PROTOCOL_CLASS 0x05
#define SCCP_SEGMENTING_REASSEMBLING 0x06
#define SCCP_RECEIVE_SEQUENCE_NUMBER 0x07
#define SCCP_SEQUENCING/SEGMENTING 0x08
#define SCCP_CREDIT 0x09
#define SCCP_RELEASE_CAUSE 0x0a
#define SCCP_RETURN_CAUSE 0x0b
#define SCCP_RESET_CAUSE 0x0c
#define SCCP_ERROR_CAUSE 0x0d
#define SCCP_REFUSAL_CAUSE 0x0e
#define SCCP_DATA 0x0f
#define SCCP_SEGMENTATION 0x10
#define SCCP_HOP_COUNTER 0x11
#define SCCP_IMPORTANCE 0x12
#define SCCP_LONG_DATA 0x13

#endif /* PLUGINS_SCCP_INC_SCCPCONSTANTS_H_ */
